# -*- coding: utf-8 -*-
"""file.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PqB1AH9Qx2qIH2ghmk6e495LOMS-xgHt

# PML Practise
"""

import pandas as pd
import numpy as np

df = pd.read_csv('Housing.csv')
df.head()

df = pd.get_dummies(df,drop_first = True)
df.head()

X = df.drop('price',axis = 1)
y = df.loc[:,'price']

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.3,random_state = 2021)



"""# Random Forest"""

from sklearn.ensemble import RandomForestRegressor
dtr = RandomForestRegressor()

from sklearn.model_selection import RandomizedSearchCV
from sklearn.model_selection import KFold

kfold = KFold(n_splits = 10, random_state = 2021, shuffle = True)

parameters = {'max_features': np.arange(1,11)}

cv = RandomizedSearchCV(dtr, param_distributions = parameters, cv = kfold , scoring = 'r2')

cv.fit(X_train,y_train)

cv.best_score_

cv.best_params_

price = cv.predict(X_test)



my_submission = pd.DataFrame({'Actual price': y_test, ' Predicted price': price})
my_submission.to_csv('submission.csv', index=False)